export component SectionTitle {
    in property <string> text;
    in property <color> text-color: #949ba4;
    height: 20px;

    VerticalLayout {
        spacing: 3px;
        Text {
            text: root.text;
            font-size: 11px;
            font-weight: 700;
            color: root.text-color;
            overflow: elide;
        }

        Rectangle {
            height: 1px;
            background: #353535;
        }
    }
}

export component FormRow {
    in property <string> title;
    in property <length> label-width: 90px;

    HorizontalLayout {
        spacing: 6px;
        Text {
            text: root.title;
            width: root.label-width;
            vertical-alignment: center;
            font-size: 12px;
            color: #dcddde;
        }

        @children
    }
}

export component SplitterBar inherits Rectangle {
    in-out property <length> target-width;
    in property <length> min-limit: 300px;
    in property <length> max-limit: 650px;

    width: 8px;
    background: ta.has-hover ? #3e3e42 : #141414;

    Rectangle {
        width: 2px;
        height: 24px;
        background: #808080;
        border-radius: 1px;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }

    ta := TouchArea {
        mouse-cursor: col-resize;
        moved => {
            if self.pressed {
                root.target-width = (root.target-width + self.mouse-x - self.pressed-x).clamp(root.min-limit, root.max-limit);
            }
        }
    }
}
