[package]
name = "OVLTool"
version = "1.0.0"
edition = "2024"
build = "build.rs"

[lib]
name = "OVLTool"
path = "src/lib.rs"

[[bin]]
name = "OVLTool"
path = "src/main.rs"

[dependencies]
slint = "1.18.1"
byteorder = "1.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
crc32fast = "1.5.2"
rayon = "1.12.0"
rfd = "0.17.2"
flate2 = "1.1.10"
hex = "0.4.3"
walkdir = "2.5.0"
anyhow = "1.0.104"
binrw = "0.15.2"
clap = { version = "4.6.7", features = ["derive"] }
base64 = "0.23.1"
bytemuck = { version = "1.25.2", features = ["derive"] }

[build-dependencies]
slint-build = "1.18.1"
